# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e6178fc3291b4a36fee94adba154047cff4af200c84f7042939ff36c6ec8c90f0ad23716ea626222e012a5893e8a63e3977b7392750f0cba2428665e5f76de1

test:
  secret_key_base: 686a19144ef067e68a8436340a0e3b91b49846d6c8fc351e075c3cc3e3010a72a6e4e1287318239549acdd9aa9329c7084ad65acbadff1ca117bd834a5159897

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
